.Dd $Mdocdate$
.Dt MTR 8
.Os
.Sh NAME
.Nm mtr
.Nd a network diagnostic tool
.Sh SYNOPSIS
.Nm
.Op Fl abBcdefFgimnopPqrsStuvwxyzZ46
HOSTNAME ...
.Sh DESCRIPTION
.Nm
combines the functionality of the
.Sy traceroute
and
.Sy ping
programs in a single network diagnostic tool.
.Pp
As
.Sy Nm
starts, it investigates the network connection between the host
.Sy Nm
runs on and
.Sy Ns HOSTNAME
by sending packets with purposely low TTLs.  It continues to send packets with low TTL, noting the response time of the intervening routers.  This allows
.Sy Nm
to print the response percentage and response times of the internet route to
.Sy Ns HOSTNAME.
A sudden increase in packet loss or response time is often an indication of a bad (or simply overloaded) link.
.Pp
The results are usually reported as round-trip-response times in miliseconds and the percentage of packetloss.
.Sh OPTIONS

.Bl -tag -width Ds
.It Fl a, Fl -address Ar IP.ADD.RE.SS
Use this option to bind outgoing packets' socket to specific interface, so that any packet will be sent through this interface.
.Sy Note
that this option doesn't apply to DNS requests (which could be and could not be what you want).
.It Fl b, Fl -show-ips
Use this option to tell
.Sy Nm
to display both the host names and numeric IP numbers.  In split mode this adds an extra field to the output.  In report mode, there is usually too little space to add the IPs, and they will be truncated.  Use the wide report mode
.Fl w
to see the IPs in report mode.
.It Fl B, Fl -bitpattern Ar NUM
Specifies bit pattern to use in payload.
.br
Should be within range 0 - 255.
.It Fl c, Fl -cycles Ar COUNT
Use this option to set the number of pings sent to determine both the machines on the network and the reliability of those machines.  Each cycle lasts one second.
.It Fl d, Fl -display Ar MODE
Use this option to select the initial display mode
.Bl -tag -offset Ds
.It Cm 1st and 2nd bits
.br
.Sy 0
default
.br
.Sy 1
without latency information
.br
.Sy 2
with latency information
.br
.Sy 3
unicode histogram
.El
.Bl -tag -offset Ds
.It Cm 3rd bit
reserved
.It Cm 4th bit
color/mono mode, on/off
.It Cm 5th bit
audible bell (beep), on/off
.It Cm 6th bit
visible bell (flash), on/off
.It Cm 7th bit
bell for target host only, on/off
.El
.It Fl e, Fl -mpls
Use this option to tell
.Sy Nm
to display information from ICMP extensions for MPLS (RFC 4950) that are encoded in the response packets
.It Fl f, Fl -first-ttl Ar NUM
Specifies with what TTL to start.  Default is 1, `a' means auto (corresponding to TTL of the destination host).
.It Fl F, Fl -fields Ar DISPLAY-FIELDS
Use this option to specify the fields to display and their order
.Pp
Available fields:
.TS
allbox tab(%);
ll.
L%Loss ratio
D%Dropped packets
R%Received packets
S%Sent Packets
N%Newest RTT(ms)
B%Min/Best RTT(ms)
A%Average RTT(ms)
W%Max/Worst RTT(ms)
V%Standard Deviation
G%Geometric Mean
J%Current Jitter
M%Jitter Mean/Avg.
X%Worst Jitter
I%Interarrival Jitter
.TE

Examples:
.br
.Cm -F 'LSD NBAW'
.br
.Cm -F 'DR AGJMXI'
.It Fl g, Fl -graph Ar ARGUMENTS
Use this option to use the cairo based graph drawing (if available)
.Pp
Available arguments by order:
.Bl -tag -offset Ds
.It Cm 1st arg: graph type
1=dot 2=line 3=curve (default 3, curve)
.It Cm 2nd arg: viewport period
in 10sec ticks (default 6, i.e. 60sec)
.It Cm 3rd arg: legend on/off
0=disable 1=enable (default 1)
.It Cm 4th arg: multipath on/off
0=disable 1=enable (default 1)
.It Cm 5th arg: latency or jitter graph
0=latency 1=jitter (default 0, latency)
.El

Use `,' (comma) as argument separator

Examples:
.Bl -tag -width indent-two -offset Ds -compact
.It Cm -g,
all args in default (curve, 1min, legend, multipath, latency)
.It Cm -g2
line, default, default, default, default
.It Cm -g,30,,0
default, 5min, default, disable, default
.El
.It Fl i, Fl -interval Ar SECONDS
Use this option to specify the positive number of seconds between ICMP ECHO requests.  The default value for this parameter is one second.  The root user may choose values between zero and one.
.It Fl m, Fl -max-ttl Ar NUM
Specifies the maximum number of hops (max time-to-live value) traceroute will probe.  Default is 30.
.It Fl n, Fl -no-dns
Use this option to force
.Sy Nm
to display numeric IP numbers and not try to resolve the host names
.It Fl o, Fl -output Ar raw,txt,csv,json,xml
.RS
Use these suboptions for automated processing
.It Fl p, Fl -split
Use this option to set
.Sy Nm
to spit out a format that is suitable for a split-user interface
.It Fl P, Fl -port Ar PORT
The target port number for TCP traces
.It Fl Q, Fl -tos Ar NUM
Specifies value for type of service field in IP header.
.br
Should be within range 0 - 255.
.It Fl r, Fl -report
This option puts
.Sy Nm
into report mode.  When in this mode,
.Sy Nm
will run for the number of cycles specified by the
.Fl c
option, and then print statistics and exit.

This mode is useful for generating statistics about network quality.

Note that each running instance of
.Sy Nm
generates a significant amount of network traffic.  Using
.Sy Nm
to measure the quality of your network may result in decreased network performance.
.It Fl s, Fl -psize Ar BYTES
This option sets the packet size used for probing.  It is in bytes inclusive IP and ICMP headers.

If set to a negative number, every iteration will use a different, random packet size upto that number.
.It Fl S, Fl -summary
Print send/receive summary at exit
.It Fl t, Fl -tcp
Use TCP SYN packets instead of ICMP ECHO
.It Fl u, Fl -udp
Use UDP datagrams instead of ICMP ECHO
.It Fl v, Fl -version
.br
Print the installed version of
.Nm
.It Fl w, Fl -wide
This option puts
.Sy Nm
into wide report mode.  When in this mode,
.Sy Nm
will not cut hostnames in the report.
.It Fl x, Fl -cache Ar SECONDS
Cache mode. Don't ping known hops during cache-timeout period (0 means default 60 seconds).
.It Fl y, Fl -ipinfo Ar ORIGIN,FIELDS
Use this option to specify the IP info origin and its fields
.Pp
Available origins and their fields:
.Bl -tag -width indent -offset Ds
.It Cm 1 - origin.asn.cymru.com (both IPv4 and IPv6)
ASN, Route, CC, Registry, Allocated
.It Cm 2 - riswhois.ripe.net (both IPv4 and IPv6)
Route, Origin, Descr, CC
.It Cm 3 - peer.asn.shadowserver.org
Peers, ASN, Route, AS Name, CC, Org
.It Cm 4 - origin.asn.spameatingmonkey.net
Route, ASN, Org, Allocated, CC
.It Cm 5 - ip-api.com
Country, CC, RC, Region, City, Zip, Lat, Long, TZ, ISP, Org, AS Name
.It Cm 6 - asn.routeviews.org
ASN
.El

Abbreviations:
.Bl -tag -width indent-two -offset Ds -compact
.It Cm TZ
TimeZone
.It Cm Org
Organization
.It Cm DMA
Designated Market Area
.It Cm CC/RC/MC/LC
Country/Region/Metro/Local Code
.El
Examples:
.Bl -tag -width indent-two -offset Ds -compact
.It Cm -y5,2,5,7,8
ip-api.com: CC City Lat Long
.It Cm -y2,4,2
riswhois.ripe.net: CC Origin
.It Cm -y,
origin.asn.cymru.com: ASN
.El
.It Fl z, Fl -aslookup
Turn on ASN lookups. The data source is
.Lk riswhois.ripe.net
.It Fl Z, Fl -timeout Ar SECONDS
The number of seconds to keep the TCP socket open before giving up on the connection.  This will only affect the final hop.  Using large values for this, especially combined with a short interval, will use up a lot of file descriptors.
.It Fl 4
Use IPv4 only
.It Fl 6
Use IPv6 only

.Sh BUGS
Some modern routers give a lower priority to ICMP ECHO packets than to other network traffic.  Consequently, the reliability of these routers reported by
.Sy Nm
will be significantly lower than the actual reliability of these routers.
.Sh CONTACT INFORMATION
.Pp
.Pp
For more information about
.Sy Ns Nm
diagnostic tool, see web page at
.Lk http://www.bitwizard.nl/mtr
.Pp
Project's location is
.Lk https://github.com/traviscross/mtr
.Pp
This version is built from
.Lk https://github.com/yvs2014/mtr085
fork
.Sh "SEE ALSO"
traceroute(8),
ping(8),
TCP/IP Illustrated (Stevens, ISBN 0201633469)
