name: mtr085
adopt-info: mtr
base: core24
version: 0.85
summary: Full screen ncurses traceroute tool (mtr v0.85 fork)
description: |
  mtr combines the functionality of the traceroute and ping programs
  in a single network diagnostic tool
    
  Built from https://github.com/yvs2014/mtr085 fork
  with whois info, IDN, unicode, etc.

  Main project's location is https://github.com/traviscross/mtr

platforms:
  amd64:
  arm64:
  armhf:
  ppc64el:
  s390x:

grade: devel
confinement: strict

apps:
  mtr085:
    command: usr/bin/mtr
    plugs:
      - network
      - network-status
      - network-observe

parts:
  mtr:
    plugin: meson
    meson-parameters:
      - --buildtype=release
      - --prefix=/usr
      - --strip
#    source: .
    source: https://github.com/yvs2014/mtr085.git
    override-pull: |
      craftctl default
      craftctl set version="$(craftctl get version).$(git rev-list --count 97af563..HEAD)"
    build-packages:
      - git
      - sed
      - meson
      - pkgconf
      - build-essential
      - libncurses-dev
      - libidn2-dev
      - libcap-dev
      - libcap2-bin
    stage-packages:
      - libncursesw6
      - libidn2-0
      - libcap2
    prime:
      - usr/bin/mtr
      - usr/share/man/man8/mtr.8

