name: build_and_run

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_debs_on_ubuntu_and_run:
    name: Run on ${{matrix.os}} (built with ${{matrix.compiler}})
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, ubuntu-24.04, ubuntu-24.04-arm, ubuntu-26.04, ubuntu-26.04-arm, ubuntu-slim]
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: master
      - name: Install mandatory packages for building
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc clang
          sudo apt install -y devscripts debhelper meson git sed pkgconf
          sudo apt install -y libncurses-dev libcap2-bin libcap-dev
      - name: Create deb package with ${{matrix.compiler}}
        env:
          CC: ${{matrix.compiler}}
        run: ./misc/build_deb.sh
      - name: Install deb package built with ${{matrix.compiler}}
        run: sudo dpkg -i debs/mtr085_*.deb
      - name: Run on ${{matrix.os}}
        run: |
          mtr -r localhost
          mtr -vv

  build_exec_on_macos_and_run:
    name: Run on ${{matrix.os}} (built with ${{matrix.compiler}})
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-15, macos-15-intel, macos-26, macos-26-intel]
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: master
      - name: Install mandatory packages for building
        run: |
          brew update || true
          brew install meson
      - name: Create executable with ${{matrix.compiler}}
        env:
          CC: ${{matrix.compiler}}
        run: |
          meson setup _build -DCAP=false -DNLS=false
          meson compile -C _build
      - name: Run on ${{matrix.os}}
        run: |
          sudo ./_build/mtr -r localhost
          sudo ./_build/mtr -vv

  build_debs_on_debian_and_run:
    name: Run on ${{matrix.image}} (built with ${{matrix.compiler}})
    runs-on: ubuntu-latest
    container:
      image: ${{matrix.image}}
    strategy:
      matrix:
        image: [debian:12, debian:13]
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: master
      - name: Install mandatory packages for building
        run: |
          apt update
          apt install -y build-essential gcc clang
          apt install -y meson git sed pkgconf gettext
          apt install -y libncurses-dev libcap2-bin libcap-dev
      - name: Create executable with ${{matrix.compiler}}
        env:
          CC: ${{matrix.compiler}}
        run: |
          meson setup _build
          meson compile -C _build
      - name: Run on ${{matrix.image}}
        run: |
          ./_build/mtr -r localhost
          ./_build/mtr -vv

  build_exec_on_alpine_and_run:
    name: Run on ${{matrix.image}} (built with ${{matrix.compiler}})
    runs-on: ubuntu-latest
    container:
      image: ${{matrix.image}}
    strategy:
      matrix:
        image: [alpine:latest]
        compiler: [gcc, clang]
    defaults:
      run:
        shell: sh
    steps:
      - uses: actions/checkout@v6
        with:
          ref: master
      - name: Install mandatory packages for building
        run: |
          apk update || true
          apk add git meson pkgconf gcc clang libintl gettext gettext-dev ncurses-dev libcap-dev libidn-dev
      - name: Create executable with ${{matrix.compiler}}
        env:
          CC: ${{matrix.compiler}}
        run: |
          meson setup _build
          meson compile -C _build
      - name: Run on ${{matrix.image}}
        run: |
          ./_build/mtr -r 127.0.0.1
          ./_build/mtr -vv

  build_debs_on_archlinux_and_run:
    name: Run on ${{matrix.image}} (built with ${{matrix.compiler}})
    runs-on: ubuntu-latest
    container:
      image: ${{matrix.image}}
    strategy:
      matrix:
        image: [archlinux:base-devel]
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: master
      - name: Install mandatory packages for building
        run: |
          pacman -Sy --noconfirm git gcc clang meson pkgconf gettext ncurses libcap
      - name: Create executable with ${{matrix.compiler}}
        env:
          CC: ${{matrix.compiler}}
        run: |
          meson setup _build
          meson compile -C _build
      - name: Run on ${{matrix.image}}
        run: |
          ./_build/mtr -r localhost
          ./_build/mtr -vv

